### ISSUE TITLE
Castling move is missing 0-0

### ISSUE THREAD

**Issue by glaand** [marcusbuffett/command-line-chess#14]
![image](https://user-images.githubusercontent.com/17197309/39638772-982db3da-4fc7-11e8-9f7f-0525a39f3887.png)

**Comment by ddugovic** [comment]
Is this issue reproducible and if so, how?

**Comment by glaand** [comment]
The official notation of castling is 0-0 (For King side) and 0-0-0 (For Queen side) 
https://en.wikipedia.org/wiki/Castling

**Comment by ddugovic** [comment]
Ah, so it is!  (PGN uses O-O and O-O-O instead.)

**Comment by borkakoz** [comment]
Still don't work

**Comment by ClasherKasten** [comment]
Closed for the following reasons:
- There is an existing fix (namely #11)
- I couldn't reproduce the bug in the latest version (28e0705fb79f1d74e398d0ea15202bc32c714264)

If anyone still has problems with this issue, please leave a comment so the community can discuss about it.
