### ISSUE TITLE
Unable to run on Replit

### ISSUE THREAD

**Issue by ArjunSharda** [marcusbuffett/command-line-chess#30]
It seems that I can't run on Replit.
![image](https://user-images.githubusercontent.com/77706434/191781186-1eb23f0a-79bd-4568-b1dd-c0e51e17bace.png)

It seems correctly configured with replit aswell.

**Comment by ClasherKasten** [comment]
You shouldn't run `src/main.py` directly. This repository provides a `console_scripts` entry point, please navigate into the root directory and install the repository through `pip install .`, then run the `chess` command as you can see in the image below.
![replit_command-line-chess](https://user-images.githubusercontent.com/94523763/191843428-9c26105e-e447-4d1b-a9b4-8f14e9d25400.png)

If you wanna know more about why you shouldn't run scripts that are inside subdirectories, here is a [video](https://youtu.be/hgCVIa5qQhM?list=PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY) which i think explains it very well.
