### ISSUE TITLE
Replace termcolor

### ISSUE THREAD

**Issue by ClasherKasten** [marcusbuffett/command-line-chess#37]
In the process of adding the new CLI, @GauthamBellamkonda noticed that [termcolor](https://pypi.org/project/termcolor/) has a very limited color set which doesn't provide as much flexibility as we want to provide.
To fix this, we need to find another library which provides the following abilities:
- colores the output (foreground and background)
- accepts hex colors as input
- (eventually shoud have a core set of named colors (E.g. "white", "black", "blue", ...))

**Comment by GauthamBellamkonda** [comment]
@ClasherKasten, how about [colored](https://pypi.org/project/colored/)? I am willing to take up this issue as well.

**Comment by ClasherKasten** [comment]
LGTM
