### ISSUE TITLE
Make `--unicode`behaviour the standard

### ISSUE THREAD

**Issue by ClasherKasten** [marcusbuffett/command-line-chess#42]
Right now the CLI provides an option named `--unicode` or `-u` which uses unicode characters to display the pieces.
If the option isn't used, then it falls back to "normal", non-unicode characters.
In the process of switching out [termcolor](https://pypi.org/project/termcolor/) to [colored](https://pypi.org/project/colored/) We noticed that it is really hard to display a colored board with non-unicode characters.

To fix this, I decided to remove the non-unicode character support and make the `--unicode` behaviour standard.
ToDo:
- remove `--unicode` option as it is the default
- remove all the code that don't need to exist anymore (E.g. the `makeStringRep` method)

**Comment by aitorres** [comment]
Hi! I opened a PR (#43) for this issue, let me know if there's anything else I should add to it!
