### ISSUE TITLE
Integrate pre-commit into the worflow

### ISSUE THREAD

**Issue by ClasherKasten** [marcusbuffett/command-line-chess#45]
Tasks:

- Add `.pre-commit-config.yaml` with the following hooks:
    - end-of-file-fixer
    - trailing-whitespace
    - double-quote-string-fixer
    - debug-statements
    - check-ast
    - mypy
    - flake8
    - autopep8
    - add-trailing-comma
    - pyupgrade
    - reorder-python-imports
- Run `pre-commit run --all-files` once
- Eventually notice it in `CONTRIBUTING.md` under **Pull Request Process**

Hooks that are listed can be discussed. When claiming this issue and you want to add additional hooks , please first comment these hooks here so they also can be discussed.

**Comment by Abdullah-Majid** [comment]
can i be assigned this?

**Comment by Abdullah-Majid** [comment]
I don't think I have perms to push my changes - I've branched off the latest master and made the changes suggested. Wanted to get some initial feedback.

**Comment by ClasherKasten** [comment]
> I don't think I have perms to push my changes - I've branched off the latest master and made the changes suggested.

For further clarification, could you please provide the output of `git remote -v`?
My guess would be that you cloned the original repository (`marcusbuffett/command-line-chess`) and for that you probably don't have the write rights. If it is the case that you cloned `marcusbuffett/command-line-chess`, please fork the project first, push the feature on a new branch in your fork and finally open a Pull Request (PR).

> Wanted to get some initial feedback.

If you open a new PR, I can give you some feedback via review.

**Comment by mohebmithani** [comment]
@ClasherKasten I've linked PR for this issue, please review it when possible.
