### ISSUE TITLE
Git Clone Problem?

### ISSUE THREAD

**Issue by ericborgos** [marcusbuffett/command-line-chess#53]
When I run it like  !pip install cl-chess it works fine but when instead I use:
git clone https://github.com/marcusbuffett/command-line-chess
like you suggested (so it has the most recent version), it shows a different graphical version of the chess board. 
This is how it looks with pip install
![Screenshot 2023-04-18 at 07-57-10 Google Colaboratory](https://user-images.githubusercontent.com/111294209/232770126-a0053876-d8c0-4b6b-972b-0af7c782f713.png)
and this is git  clone:
![Screenshot 2023-04-18 at 07-56-53 Google Colaboratory](https://user-images.githubusercontent.com/111294209/232770128-07e80c64-257c-4ce1-a813-7ab8793b24e1.png)

I only play chess IRL, not online, so maybe I am not used to how it works, but the git clone way only shows me what the AI is doing, not my own moves. 

I should note that I am using Google Colab, so maybe somehow that is changing it. In case you want to try it, the Google Colab code is:
!git clone https://github.com/marcusbuffett/command-line-chess
%cd /content/command-line-chess
!pip install .
!chess

**Comment by ClasherKasten** [comment]
This is not a problem with command-line-chess, but with the coloring it uses as a default. But this can be changed via command-line arguments (in this case the `--white` argument, see code [here](https://github.com/marcusbuffett/command-line-chess/blob/38c47d459656accc4d5443df8e46fa581f498b58/src/main.py#L248-L255))
An example using `!chess --white="red"`:
![screenshot](https://user-images.githubusercontent.com/94523763/232777979-6abde21f-343c-45e2-9561-f13a58c157a5.png)

---
As a side note: `pip` supports installing from a git repository through `pip install git+<url-to-repository>`. Documentation can for this be found [here](https://pip.pypa.io/en/stable/topics/vcs-support/)
