### ISSUE TITLE
Google Colab Problem?

### ISSUE THREAD

**Issue by ericborgos** [marcusbuffett/command-line-chess#54]
I know you don't officially support Google Colab, but I am not sure if this is a problem only with Colab or not (I don't run Python locally so I have not tried it without Colab). In Colab when I install via git clone like:
!pip install git+https://github.com/marcusbuffett/command-line-chess
and run it like:
!chess --white="red"
it does not correctly show the position of the pieces that were moved. It looks like this:
![Screenshot 2023-04-18 at 08-43-53 Google Colaboratory](https://user-images.githubusercontent.com/111294209/232781649-da7dcbf0-db68-4754-9463-74f4d44c123b.png)
If I instead use your old version by installing it like:
!pip install cl-chess
it works fine, see below:
![Screenshot 2023-04-18 at 08-47-31 Google Colaboratory](https://user-images.githubusercontent.com/111294209/232782061-a300922b-9ae7-40c2-b0b9-602d437f7d5b.png)

**Comment by ClasherKasten** [comment]
This is a google colab problem. command-line-chess uses unicode characters for representing the pieces, so i guess colab has some problems with
 these. This can be seen when using the `--checkered` option:
![Screenshot_20230418_154921](https://user-images.githubusercontent.com/94523763/232798318-192b4794-1388-49f4-b7ce-27a1e77ffc4a.png)
