### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by mr0riiz** [marcusbuffett/command-line-chess#8]
Hello, i am having problems installing this. 

i tried pip3 install cl-chess 

and i get the answer: 

Could not find any downloads that satisfy the requirement cl-chess
Cleaning up...
No distributions at all found for cl-chess

do you know a solution to this?

thank you :-)

**Comment by igor822** [comment]
@mr0riiz I had to clone the project and install by myself.

**Comment by marcusbuffett** [comment]
Well it took me almost 4 years, but I've finally figured out this issue. Should be able to install from pip now :smile:
